Unit 3 mini projects
shift-up/Web-Dev-Advanced pull request #4
Opened 2020-11-29 16:32 UTC by ecwalsh

This is just the mini-project READMEs for what's currently in the roadmap. 

I think we should consider adding more React content. The OpenClassrooms guide suggests we only have around 10 hours of content in unit 3.1, and from what I can tell it only scratches the surface of React. I feel that a strong grasp of a front-end framework is going to be more valuable to students looking for their first junior role than some of the other roadmap content to which more time is devoted in the current roadmap (e.g. +20 hours mockups/wireframes, 10 hours security). More advanced topics like hooks, routing, state management could all be touched on after unit 3.1.

2020-12-02 15:32 UTC, alaurenz requested changes

2020-12-02 15:32 UTC, alaurenz commented on Unit3/Module3.1/Mini-project3.1a/README.md
> +2. Create a new branch and then new Pull Request and assign it to your coach for review.
Here it is probably helpful to tell them what specific files they should be putting into the PR (referring to files that they would be building out according to OpenClassroom instructions).

2020-12-02 15:32 UTC, alaurenz commented on Unit3/Module3.1/Mini-project3.1b/README.md
> +2. Create a new branch and then new Pull Request and assign it to your coach for review.
Again, same as above, lets tell them what specific files they should be putting into the PR.

2020-12-02 15:32 UTC, alaurenz commented on Unit3/README.md
> +   * Mini-Project 3.1a: [Add a Validation Message](https://openclassrooms.com/en/courses/4286486-build-web-apps-with-reactjs/4317901-practice-add-a-validation-message)
Similar comment as in my Unit 1 PR, make sure the links point to the READMEs in a relative way.

2020-12-06 19:07 UTC, raevangregson commented
I think that this [React tutorial](https://reactjs.org/tutorial/tutorial.html) from the React documentations hits a few more concepts in depth - it should be easy to follow, since it has example code through out as well as the final code pen at the end.

2020-12-13 17:21 UTC, raevangregson approved these changes
It looks like you addressed adrians comments - going to approve and merge, and open a PR of my own.

2020-12-13 17:21 UTC, merged